// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wwajzpuhippuojsefvzr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Ind3YWp6cHVoaXBwdW9qc2VmdnpyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY2MDE3NjQsImV4cCI6MjA3MjE3Nzc2NH0.gHQmBi323Lw0eY9u9gDAOTvGKTs9JJaubbYu2t3YcP0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});