name: Solo Release

on:
  workflow_dispatch:
    inputs:
      bump:
        description: "Version bump (patch | minor | major)"
        required: false
        default: patch
  push:
    branches:
      - main
    tags:
      - 'v*'

permissions:
  contents: write

env:
  GH_TOKEN: ${{ secrets.GH_TOKEN }}

jobs:
  autotag:
    if: startsWith(github.ref, 'refs/heads/')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Compute next version
        id: ver
        shell: bash
        run: |
          set -euo pipefail
          LAST_TAG=$(git describe --tags --abbrev=0 2>/dev/null || echo v0.0.0)
          BUMP="${{ github.event.inputs.bump || 'patch' }}"
          BASE=${LAST_TAG#v}
          IFS='.' read -r MA MI PA <<< "$BASE"
          case "$BUMP" in
            major) MA=$((MA+1)); MI=0; PA=0 ;;
            minor) MI=$((MI+1)); PA=0 ;;
            *)     PA=$((PA+1)) ;;
          esac
          NEXT="v${MA}.${MI}.${PA}"
          echo "last=$LAST_TAG" >> "$GITHUB_OUTPUT"
          echo "next=$NEXT" >> "$GITHUB_OUTPUT"

      - name: Create and push tag
        run: |
          git tag -a "${{ steps.ver.outputs.next }}" -m "Release ${{ steps.ver.outputs.next }}"
          git push origin "${{ steps.ver.outputs.next }}"

  release:
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
      - name: Install gh
        run: |
          sudo apt-get update
          sudo apt-get install -y gh

      - name: Create GitHub Release (auto notes)
        run: |
          gh release create "$GITHUB_REF_NAME" \
            --title "$GITHUB_REF_NAME" \
            --generate-notes
